### ISSUE TITLE
Chapter positions are wrong

### ISSUE THREAD

**Issue by kakaroto** [captn3m0/cosmere-books#3]
Tried the script, thanks for that. I sent a PR #2 already, but I never did any ruby (and not willing to learn it either) so I'm filing an issue instead for this.
In the epub format, going directly to chapters in the table of contents jumps to the wrong page for some reason. It seems to be a few pages beyond the actual chapter. I tried Chapter 1, it jumped to page 17 instead of 13, and Chapter 7 jumps to page 90 insetad of 79. So it's not even a constant offset.

**Comment by captn3m0** [comment]
Which book are you reporting this for? 

I'm assuming Oathbringer, but just want confirmation.

**Comment by kakaroto** [comment]
Yes, for Oathbringer, and my reader is "[Icecreame ebook reader](https://icecreamapps.com/Ebook-Reader/)" for Windows.

**Comment by captn3m0** [comment]
Thanks, Can you send me a copy of the generated EPUB you are using to <me@captnemo.in>. I'm letting pandoc decide on the chapter headers, so I don't have much clue as to why this might be happening. Might be easier to debug with the EPUB itself.

**Comment by captn3m0** [comment]
Still haven't figured out what's the exact issue. The syntax is correct, and the links point to the right files, and it navigates perfectly for all of my readers (KO Reader, Calibre, lucidor). But I've noticed something similar to the issue in calibre:

On clicking at Chapter 10, while calibre switches to the correct position, it marks chapter 9 as current. Happens with other chapters as well.

I'm learning more about EPUBs everyday.

**Comment by captn3m0** [comment]
Oathbringer is released. Go buy that instead!
