### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by kakaroto** [captn3m0/cosmere-books#4]
In the epub, the chapter number and title are left aligned while the entire chapter text itself is center-aligned. It makes for a weird reading experience when all the text is centered.
I've checked the html file it generated, and it seems to center align the chapter title only, then right justify the epigraph, then the text is normal, but that's not what I see in the epub, so is this a configuration issue or a bug in pandoc ?

**Comment by captn3m0** [comment]
I've been happily reading this on my KOReader with no issues, but I might have disabled embedded styles there.

I've noticed the center alignment in some EPUB readers, but haven't figured out how to fix it yet. What reader are you using?

**Comment by kakaroto** [comment]
Thanks, I confirm that this was fixed for my reader, and for future reference, I use "[Icecream ebook reader](https://icecreamapps.com/Ebook-Reader/)" for Windows.
