### ISSUE TITLE
Windows can't find ebook-convert

### ISSUE THREAD

**Issue by Enviii** [captn3m0/cosmere-books#6]
I'm on Win10. I have Calibre installed. I can run `ebook-convert` via command line and get the man page, but running `ruby oathbringer.rb` with an output of :mobi will always result in: 

[html] Generated HTML file
[error] Can't generate MOBI without ebook-convert
[error] Please check README for PDF dependencies

I have all other dependencies (except PDF, but I'm running :mobi specifically). 

Edit: Ran it in my Ubuntu VM and it worked fine. Windows still does not work.

**Comment by captn3m0** [comment]
Thanks for the report.

Can you try the following in your console:

```
 irb
2.4.1 :001 > require './methods'
 => true 
2.4.1 :002 > command? 'ebook-convert'
 => "/usr/bin/ebook-convert" 
```

**Comment by Enviii** [comment]
This was the output: 

`λ irb`
`irb(main):001:0> require './methods'`
`=> true`
`irb(main):002:0> command? 'ebook-convert'`
`=> nil`
`irb(main):003:0>`
